### ISSUE TITLE
Cookies?

### ISSUE THREAD

**Issue by paulsapps** [lamchakchan/RestAssured.Net#22]
How do I set a cookie?

**Comment by lamchakchan** [comment]
I didn't implement a `cookies` interface.  But the current framework can support it if you utilize the `Header` setter.  Create a `Header` key with the name of `Cookie` and the value needs to be a comma delimited string of key/value pairs.  

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie
