### ISSUE TITLE
Questions about RestAssured.Net

### ISSUE THREAD

**Issue by antgel** [lamchakchan/RestAssured.Net#27]
Thanks for this project. I sent an email, but no answer, so turning to the community.

I have some questions about it. Is it actively maintained? Is it designed to keep up with all features of the Java version, or does it go its own way? Is it a must when testing a .NET API, or is it possible to integrate the Java version too? I'm thinking about things like creation and destruction of the test database.

**Comment by antgel** [comment]
@lamchakchan Ping?

**Comment by antgel** [comment]
@RobertSandu I never understand why maintainers ghost. flurl looks interesting, it hadn't come up in my searching. Thanks a lot!

**Comment by RobertSandu** [comment]
@antgel They loose their interest or they don't have enough time. But as long as the project si free and opensource I think it's ok to do that. Anyone can fork the project and continue the work.

**Comment by antgel** [comment]
Sure. But it takes about five minutes to update the community so we aren't left guessing.
